# logging
logging.level.root: ERROR
logging.level.company.challenge: INFO
logging.level.org.springframework.web: ERROR

api.key: YOU_KEY_HERE

open-weather-map:
  ribbon:
    listOfServers: api.openweathermap.org:80

spring:
  jackson:
    serialization.write_dates_as_timestamps: true
